export const projectsData = [
  {
    id: "reports-api",
    title: "Reports API",
    category: "Backend / DevOps",
    description:
      "Enterprise-grade REST API for Problem Reporting System built with Go. Implemented complete DevOps infrastructure with Docker, Nginx, and CI/CD automation.",
    longDescription: `This is a comprehensive REST API system designed for enterprise-level problem reporting. The project demonstrates advanced backend engineering with a complete DevOps infrastructure, making it production-ready with high availability and security.`,
    image: "/golang-rest-api-backend-system.jpg",
    highlights: [
      "Designed and implemented RESTful APIs using Go",
      "Set up MySQL database with optimized schema design",
      "Configured Nginx with reverse proxy, load balancing, and security",
      "Created CI/CD pipeline with Docker, GitHub Actions, and Docker Hub",
      "Implemented Docker Swarm for cluster management",
      "Integrated Telegram bot for notifications",
      "Set up MinIO for scalable image storage",
      "Generated comprehensive API documentation with Swagger",
    ],
    technologies: [
      "Go",
      "MySQL",
      "Docker",
      "Nginx",
      "GitHub Actions",
      "Docker Swarm",
      "MinIO",
      "Telegram API",
      "Swagger",
    ],
    links: {
      github: "https://github.com/PanithanPK/reports-api",
      demo: "https://github.com/PanithanPK/reports-api",
    },
    keyLearnings: [
      "Set up a server for installing and configuring MySQL, Nginx, Docker, and Git",
      "Designed a database using DrawDB.app and implemented data storage using MySQL",
      "Configured Nginx with DNS integration, reverse proxy, load balancing, firewall, and logging",
      "Implemented a DevOps workflow using Docker to automate server builds through GitHub Actions, GitLab CI, or Jenkins",
      "Created a CI/CD pipeline that builds images to Docker Hub and automatically pulls them to the server",
      "Learned to use Docker Swarm for cluster management",
      "Learned Go (Golang) for developing RESTful APIs and managing databases through API endpoints",
      "Integrated a Telegram bot for user interaction",
      "Used MinIO for image storage",
      "Created API documentation using Go Swagger",
      "Maintained detailed project documentation on GitHub including server setup guides",
    ],
  },
  {
    id: "fall-detection",
    title: "Fall Detection System",
    category: "AI / Computer Vision",
    description:
      "Intelligent fall detection system using computer vision and AI. Monitors individuals using cameras and triggers alerts when falls are detected.",
    longDescription: `An advanced AI-powered monitoring system that detects falls in real-time using computer vision. The system is designed to run on edge devices like Jetson Nano while providing a comprehensive web interface for monitoring and alert management. Perfect for elderly care, healthcare facilities, and safety applications.`,
    image: "/ai-fall-detection-camera-system.jpg",
    highlights: [
      "Implemented real-time fall detection using computer vision",
      "Deployed on Jetson Nano for edge computing",
      "Created responsive web interface for monitoring",
      "Integrated alert notification system",
      "Supports both webcam and IP camera feeds",
      "Video stream processing and analysis pipeline",
      "Real-time alert triggering and logging",
      "Scalable architecture for multiple camera feeds",
    ],
    technologies: ["Python", "OpenCV", "AI/ML", "Jetson Nano", "Web Interface", "Real-time Processing", "Alert System"],
    links: {
      github: "https://github.com/PanithanPK/Fall-Detection-System-using-Camera-and-Alert-Notification",
      demo: "https://github.com/PanithanPK/Fall-Detection-System-using-Camera-and-Alert-Notification",
    },
    keyLearnings: [
      "Implemented advanced computer vision algorithms for real-time fall detection",
      "Optimized AI models to run efficiently on edge devices like Jetson Nano",
      "Built a responsive web interface for real-time monitoring",
      "Integrated multi-camera support with fallback mechanisms",
      "Implemented efficient video processing pipelines",
      "Created robust alert notification systems",
      "Learned to deploy AI applications on resource-constrained hardware",
      "Developed scalable architecture for handling multiple concurrent streams",
    ],
  },
]
